version: '3.8'

services:
  frontend:
    build:
      context: .
      target: frontend-builder
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app/frontend
      - ./controllers:/app/controllers
      - ./models:/app/models
      - /app/frontend/node_modules
    command: npm run dev

  api:
    build:
      context: .
      target: backend-builder
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./api:/app/api
      - ./controllers:/app/controllers
      - ./models:/app/models
      - ./queues:/app/queues
      - ./websocket:/app/websocket
      - ./uploads:/app/uploads
      - /app/node_modules
    depends_on:
      - redis

  websocket:
    build: .
    ports:
      - "5002:5002"
    command: ["npm", "run", "websocket"]
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: