version: "3.8"

services:
  frontend:
    build:
      context: .
      target: frontend-builder
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app/frontend
      - ./uploads:/app/frontend/public/static # Frontend acessa uploads
    working_dir: /app/frontend
    command: npm run dev

  api:
    build: .
    ports:
      - "3000:3000"
    command: ["node", "api/index.js"]
    volumes:
      - ./uploads:/app/uploads # API também acessa

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./uploads:/usr/share/nginx/html/static # NGINX serve os arquivos
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  websocket:
    build: .
    ports:
      - "5002:5002"
    command: ["node", "websocket/index.js"]

  redis:
    image: redis:alpine
    ports:
      - "6123:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
