# Generated by Django 3.1.2 on 2020-11-12 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='service',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
